name: Test

on:
    pull_request:
    workflow_dispatch:

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
         - name: Checkout Branch
           uses: actions/checkout@v4
         - name: Run Cargo check
           run: cargo check
